# Generated by Django 5.2 on 2025-08-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_registation_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='registation',
            name='Email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
