# Generated by Django 5.2 on 2025-08-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_registation_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registation',
        ),
    ]
